### ISSUE TITLE
Cannot find module 'js-beautify'

### ISSUE THREAD

**Issue by LeeHarlan** [Qymh/vue-router-invoke-webpack-plugin#24]
**Describe the bug**
引用 0.4.1 版本启动 vue 项目会出现 Cannot find module 'js-beautify'

**Version**
`vue-router-invoke-webpack-plugin`: 0.4.1
`webpack`:
`node`:
`system`: [windows or mac]

** The tree of files or Screenshots**
```
Error: Cannot find module 'js-beautify'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (vue-demo/node_modules/vue-router-invoke-webpack-plugin/core/files.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

**Comment by Qymh** [comment]
依赖包放错位置了 0.4.2 版本修复了 @LeeHarlan
